### ISSUE TITLE
Adjust colors for CLI tool on light background

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#107]
In #103 we have implemented colors for CLI. They can look a bi better on white background.

## Steps:
1. Find a way to detect if background is light or dark
2. Generate more readable colors on light background
3. Test few popular terminal color schemes and also adjust colors for dark and light backgrounds 

### Light background screenshot: 
![screen shot 2017-01-17 at 15 08 14](https://cloud.githubusercontent.com/assets/96552/22023646/48a51e62-dcc7-11e6-9dad-0f5a18bb2d67.png)

**Comment by netme** [comment]
Also checked how homebrew behaves:

![screen shot 2017-01-17 at 15 23 07](https://cloud.githubusercontent.com/assets/96552/22024048/fb5bd63a-dcc8-11e6-8874-c596ceaf4aff.png)

![screen shot 2017-01-17 at 15 23 31](https://cloud.githubusercontent.com/assets/96552/22024047/fb40e58c-dcc8-11e6-94a6-b340623b69bf.png)

**Comment by netme** [comment]
![screen shot 2017-01-17 at 15 23 31](https://cloud.githubusercontent.com/assets/96552/22024115/2c40cda0-dcc9-11e6-98e1-b5c6881d10c4.png)

**Comment by netme** [comment]
I did some experiments with different color schemes. So far the colors we are using (red, green, yellow and cyan) are looking good in the most of terminals:

![screen shot 2017-01-18 at 19 06 21](https://cloud.githubusercontent.com/assets/96552/22076697/78cdbbe0-ddb1-11e6-810d-593308e8fec4.png)

Proposal: to keep it as it is for now.

**Comment by netme** [comment]
@fmueller , @maxim-tschumak any thoughts?

**Comment by maxim-tschumak** [comment]
Looks great! I would keep them :)

**Comment by netme** [comment]
Thanks @maxim-tschumak for checking!

**Comment by netme** [comment]
@fmueller , waiting for your feedback on this topic

**Comment by fmueller** [comment]
I agree, looks good.
