### ISSUE TITLE
Replace Bats Framework for Integration Testing

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#108]
`Bats` framework is doing its job now, but sometimes it's nightmare to debug it when something is changing on CLI.

## Steps:
1. Find a better tool to test CLI and discuss it with Zally team
2. Reimplement existing integration tests
3. Adjust `.travis.yml`

**Comment by netme** [comment]
@mkulak since you now feel the pain of Bats framework as well, how about kotlinizing the integration tests? ;-)

**Comment by fmueller** [comment]
This has low priority for me. Let's concentrate on improving UX in CLI first.

**Comment by innokenty** [comment]
Closed via #456
