### ISSUE TITLE
Introduce Code Quality Tools to the Project

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#113]
In order to keep the codebase clean, we should introduce some code quality checking tools like PMD or CheckStyle for Java.

Since we also supporting Kotlin for the rule definitions, we also need to check tooling around this language.

**Comment by maxim-tschumak** [comment]
Error-prone is also a good option. (http://errorprone.info/)

**Comment by netme** [comment]
@maxim-tschumak , yeah, looks like a good addition to other tools. We can use multiple of them.

**Comment by mkulak** [comment]
We could look at: https://github.com/shyiko/ktlint

**Comment by netme** [comment]
@mkulak thanks for the link. It looks good to me, we can give it a try.

**Comment by netme** [comment]
⬆️  first part, more to come.

**Comment by fmueller** [comment]
Because Kotlin as a language does not have so good integration into SaaS code quality tools, it's ok to have it integrated into the build.

For Java we can do the same with Findbugs and PMD. But I also like Codacy (https://www.codacy.com) because they are integrating smoothly with our PR-flow. What do you think?

**Comment by netme** [comment]
@fmueller thanks for your input.

Codacy looks nice, I really like how it's integrated with our pull requests, we can benefit from it.

From another hand, if we will go with PMD + FindBugs (and maybe + CheckStyle), we can use them locally during the development process, this will also protect us from pushing lower quality code. 

We can also use errorprone instead of Findbugs because it operates on source instead of bytecode.

Thoughts?

**Comment by netme** [comment]
Since this task is becoming quite big, opened 2 extra tickets #123 and #124 with leftovers. Closing this one.
