### ISSUE TITLE
Introduce Test Coverage Tool

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#125]
### Steps:
1. Find a good tool for measuring test coverage (preferable with GH integration)
2. Introduce it to the zally builds
3. Add a badge to `README.md`

**Comment by fmueller** [comment]
I think, we should also use Codacy for code coverage: https://support.codacy.com/hc/en-us/articles/207993835-Add-coverage-to-your-repo

**Comment by netme** [comment]
Yes, makes sense. Already mentioned it before in chat :-)

**Comment by netme** [comment]
Got a message from Codacy:

```
 Oops! We weren't able to validate your report. Ping us on the support chat and we will help you figure it out.
What might be wrong?
Outdated reporter: Always make sure you are running an up-to-date version of the reporter.
Inconsistent file paths: Depending on your project structure, we may be unable to automatically detect the files identified in your coverage report. The reporters have special options to normalise the project root folder, check their documentation.
```

Will check it later.
