### ISSUE TITLE
Rule: Detect base path property is not used

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#139]
Introduce a new rule which detects if a base path can be extracted out of all resource names. If all paths have same path prefix, a could violation should be created.

**Comment by fmueller** [comment]
@netme Can also be a hint rule... ;)

**Comment by netme** [comment]
@fmueller actually yes, can be a nice first example.

**Comment by fmueller** [comment]
I saw this issue during an API review I did where team missed using basePath property which cause some other violations.

**Comment by netme** [comment]
Current status: server part is implemented in #146, CLI should be adjusted.

**Comment by netme** [comment]
Closing this one since I've found a special ticket for CLI: #90
