### ISSUE TITLE
Give information about not-automated rules

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#140]
As user of Zalando's API Linter I'd like to know which rules are not yet automated. This would improve API design process because as an API provider I would know which rules I should read. Furthermore it would help API reviewers to know on which aspects to concentrate because they are not covered by Zally.

Server should deliver in api-violations response a simple description text about not yet automated rules. This text should be configurable. CLI should display this text as part of summary.

**Comment by netme** [comment]
Nice idea, I like it! 

> Server should deliver in api-violations response a simple description text about not yet automated rules. 

Should it be a list of rules instead?

**Comment by fmueller** [comment]
I think it should be just a text field (to keep it as open as possible for other users of our API linter). You can also provide a bullet point list in this text field - it's up to you what you write in the configuration for this text field.

Server should deliver this extra text field by default. We can make displaying of this text optional in CLI tool or having a flag to disable it.

**Comment by netme** [comment]
@fmueller, clear. Should we hard-code that message for now?

**Comment by fmueller** [comment]
I would start with a simple text variable read from spring config files. No need for hard-coding I think.
