### ISSUE TITLE
Show warning unused resources

### ISSUE THREAD

**Issue by ehrlichandreas** [zalando-incubator/zally#152]
It would be nice, if zally warned, that some resources like `definitions`, `parameters` or `tags` are not used. Just like in [Swagger Editor](http://editor.swagger.io/).
It would save a lot of copy paste time.

**Comment by fmueller** [comment]
You mean, a hint for "unused swagger elements" like "unused imports" in java? So, I declared a definition in my swagger file and not use it anywhere.

**Comment by ehrlichandreas** [comment]
Yes, that's what I mean.

**Comment by fmueller** [comment]
I close this for now and we improve this step by step with user feedback.

Thanks @mkulak Great piece of code :)
