### ISSUE TITLE
Add rule for extensible enums

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#160]
If enum is used for a field a should rule violation should be fired because we recommend usage of `x-extensible-enum`, see http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html ("Should: Used Open-Ended List of Values (x-extensible-enum) Instead of Enumerations")

**Comment by ePaul** [comment]
Possibly this could be restricted to objects used for server → client communication (assuming the server is the API owner)? For client → server, enum is fine (and extensible).

**Comment by netme** [comment]
Moving temporary back

**Comment by maxim-tschumak** [comment]
We cannot implement this rule with the Swagger parser since this information is transparent.

@fmueller @netme can you confirm? How do we want to proceed?

Drop this rule or implement an own swagger parser?

**Comment by ePaul** [comment]
> We cannot implement this rule with the Swagger parser since this information is transparent.

You mean Swagger-Parser doesn't support vendor extensions?
That surprises me.
(Also, at least you can check whether there is `enum´ and warn against that.)

**Comment by maxim-tschumak** [comment]
@ePaul @netme my bad - thanks for the input. I'll double check.

**Comment by maxim-tschumak** [comment]
@netme 
> You can use the enum keyword to specify possible values of a request parameter or a model property.

(from [Swagger Specs](http://swagger.io/docs/specification/enums/))

I'm working on it.
