### ISSUE TITLE
UI as standalone component

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/zally#170]
To increase the flexibility, to increase independence and ease the contributions of Frontend Developers I think it would make sense to have the UI as a separate component using a frontend friendly stack.
The UI will be stateless and communicating with the server only via the exposed REST API.

WDYT?

**Comment by fmueller** [comment]
As discussed with @rbarilani: it makes sense to already migrate our web ui right now as the IAM integration is quite hard with our current architecture.
