### ISSUE TITLE
Add linting and code coverage.

### ISSUE THREAD

**Issue by bhaskarmelkani** [zalando-incubator/zally#179]
- [x] Add Linting

- [ ] Add Unit Tests(Server)

- [ ] Add Unit Tests(Client)

- [ ] Code Coverage(Reports)

- [ ] Update Travis

- [ ] Codeclimate

- [ ] Badges

**Comment by mfellner** [comment]
We should consider using https://github.com/prettier/prettier for code formatting. It's already widely adopted in the JS community and solves all code formatting headaches in pull requests.

**Comment by bhaskarmelkani** [comment]
#212 For unit tests of client.

**Comment by bhaskarmelkani** [comment]
#213 for TravisCI and coverage.
