### ISSUE TITLE
Build web-ui with Gradle

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/zally#180]
This is a follow-up to #170. We could streamline the build process by using a [Gradle plugin for NodeJS](https://plugins.gradle.org/plugin/com.moowork.node) to build the Web UI together with the backend.

```groovy
apply plugin: 'com.moowork.node'

node {
  version = '7.7.1'
}

assemble.dependsOn(npm_install)
```

The plugin would have to operate on the web-ui directory outside of the server directory, so I'm not 100% sure that it would actually work. The plugin [should be configurable](https://github.com/srs/gradle-node-plugin/blob/master/docs/node.md#configuring-the-plugin).

**Comment by rbarilani** [comment]
@mfellner @fmueller can we consider this one invalid since the web-ui project moved [here](https://github.com/zalando-incubator/zally-web-ui)?
