### ISSUE TITLE
UseProblemJsonRule is incorrect

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#182]
Current implementation of UseProblemJsonRule is incorrect:
```
if (httpCode in 400..599 && responseEntry.value?.schema?.type != "ref") { //TODO MK: implement real check for Problem usage
    listOf("${pathEntry.key} ${opEntry.key} ${responseEntry.key}")
} else emptyList()
```

It checks only for `schema.type` being ref. 

*DoD:*
UseProblemJsonRule checks whether error response is json object with problem structure (including ref to such object)

**Comment by fmueller** [comment]
Good finding. I would make it more liberal: response should be ref to ProblemJson or object corresponding to problem json object structure.
