### ISSUE TITLE
Move fetch api definition feature to Zally API

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#198]
The web ui currently does the fetching of an api definition which is given via an url by the user. The web ui implements this on server side in Node.

Let's discuss if we should change our Zally API to also accept links to api definition files. There are different ways of designing this:

- adding new endpoint only for urls
- adding new optional field in payload of current `api-violations` endpoint
- transparently accepting a link in current `api_definition`field

Looking for feedback from you, @netme @mkulak @rbarilani. Do you wanna have this in Zally API? And if yes, which design do you prefer?

**Comment by netme** [comment]
@fmueller, nice summary 👍 

I will go for option 2:

> adding new optional field in payload of current api-violations endpoint

Reason: the responsibility of `/api-violations` stays the same, it just a way how you define the API, by URL or providing a JSON.

**Comment by rbarilani** [comment]
@fmueller I am for the third option because I like keep the api surface smaller as possible so or you provide a schema or you provide a link to a schema.

**Comment by mkulak** [comment]
Don't have strong preference here. 
Option 2 looks slightly better (b/c of not overloading field meaning)

**Comment by fmueller** [comment]
Ok, then we'll go with option 2:

- adding `api_definition_url` field
- making both fields, `api_definition` and `api_definition_url`, optional
- returning `BAD_REQUEST` if none of them is in the request or both (the API only accepts one field at once)

**Comment by netme** [comment]
Btw, we should also move it out of `cli` component.
