### ISSUE TITLE
Several rules that checks json are doing it wrong 

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#202]
Common pattern for checking json: iterate over content of **definitions** section.
This approach has 2 issues:
 - in-place definitions in paths are skipped
 - definitions inside other definitions are skipped

Full list of affected rules:
`AvoidSynonymsRule.kt`, 
`CommonFieldNamesRule.kt`
`PluralizeNamesForArraysRule.kt`
`SnakeCaseInPropNameRule.kt`

Suggestion: introduce abstract DefinitionsRule (like HttpHeadersRule) that will take care of properly iterating over all json definitions.

**Comment by fmueller** [comment]
Good point, I also like your solution proposal.
