### ISSUE TITLE
Zally should report at least a warning if HTTP scheme is used in combination with OAuth2.0

### ISSUE THREAD

**Issue by duergner** [zalando-incubator/zally#208]
OAuth2.0 enforces HTTPS as protocol but Zally does not report at least a warning if the spec has both `http` and `https` as schemes defined in combination with `oauth2` as security definition.

**Comment by ePaul** [comment]
Could we have a warning for all HTTP usages? I think all our APIs (maybe apart from monitoring endpoints just accessible inside the AWS account) should use HTTPS.

**Comment by netme** [comment]
@duergner , @ePaul do you know if we have a special rule for that? If not, we can make this check as a part of [Must: Secure Endpoints with OAuth 2.0](http://zalando.github.io/restful-api-guidelines/security/Security.html) rule

**Comment by ePaul** [comment]
Hmm, I didn't see any on a short look. I guess if OAuth 2.0 is a MUST (I was not aware of that), it might be seen as included there.

**Comment by duergner** [comment]
If you submit OAuth Bearer tokens the endpoint MUST be HTTPS. HTTP would allow to sniff the tokens.

Monitoring endpoints which are only accessed by ZMON appliance inside the same AWS (and therefore maybe exposed via HTTP (which is only valid of they require no OAuth token IMHO)) should not be part of the public API anyway (again IMHO)

**Comment by ePaul** [comment]
Not part of the public API, but maybe you want to review the internal API too? Or is this out-of-scope for Zally?

**Comment by duergner** [comment]
Do you see benefits in reviewing this type of internal APIs? They are mostly defined a priori by the consuming side anyway and/or follow industry standards. (Spring Actuator Metrics, Prometheus, etc.)

**Comment by fmueller** [comment]
I don't see an issue to check for HTTPS if OAuth is enabled in an API - otherwise OAuth is not secure and the API producer should be informed about this.

**Comment by netme** [comment]
@ePaul, @duergner , @fmueller thanks for your feedback.
So we will go with modifying the existing `MUST` rule in this case?
