### ISSUE TITLE
Increase the length for the 'Base path can be extracted' Hint ?

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#210]
@maschleg and I have got this hint when checking our brand new API :)

```
Found the following HINT violations
===================================

Base path can be extracted
  All paths start with prefix '/ap'. This prefix could be part of base path.
  http://zalando.github.io/restful-api-guidelines/naming/Naming.html
```

We have multiple paths which start with `/ap`: `/api`, `/applications`, etc.

The rule definitely makes sense. Though, I believe increasing the length would make the hint more effective. Alternatively, we can have this hint only for paths which have the same word in the prefix: `api-version`, `api-definition` -> `api/version`, `api/definition`.

**Comment by mkulak** [comment]
Looks like bug

**Comment by fmueller** [comment]
Reproduced it with https://raw.githubusercontent.com/zalando-incubator/api-discovery/master/storage/src/main/resources/api/api-repository-api.yaml

**Comment by mkulak** [comment]
Will work on it
