### ISSUE TITLE
Create GitHub page for Zally

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#223]

**Comment by netme** [comment]
As discussed with @fmueller , taking over this ticket

**Comment by netme** [comment]
Created an orphan branch: https://github.com/zalando-incubator/zally/tree/gh-pages

**Comment by netme** [comment]
### What's done so far:
- [x] Created an (orphan branch)[https://gist.github.com/seanbuscay/5877413]
- [x] Added logo
- [x] Fixed links

### Ideas to improve:
- [ ] Merge TODO and Contributing sections
- [ ] Update Roadmap for 1.1 and 1.5
- [ ] Add a Quickstart guide

**Comment by netme** [comment]
@fmueller , @mkulak could you please check what is still missing on our (GH page)[https://zalando-incubator.github.io/zally/] ?

**Comment by mkulak** [comment]
@netme good enough
Maybe add line about web UI? Perhaps even provide link to deployed instance?

**Comment by netme** [comment]
@mkulak thanks for checking!
We should definitely mention `web-ui`. Maybe providing a link is not the best idea since it's still a private Zalando service, but providing good setup instructions will definitely bring some value.

**Comment by netme** [comment]
Fixed missing parts in #303
