### ISSUE TITLE
Improve error message when API definition cannot be parsed

### ISSUE THREAD

**Issue by mfellner** [zalando-incubator/zally#252]
**What**
Improve the error response when an API definition cannot be parsed (validated as OpenAPI compliant).

**Why**
Currently the violations API returns an error detail "NullPointerException" if SwaggerParser cannot parse the API definition. SwaggerParser.parse() only returns null when a definition cannot be parsed so the Exception caught in RulesValidator and used for the error response is always a NullPointerException.

**Proposal**
Use a static string for the error description.

**Comment by fmueller** [comment]
Good point 👍
