### ISSUE TITLE
Should Problem JSON check more liberal?

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#258]
Currently we assume that all fields of Problem JSON have to be in the payload - and we check for this. I'd like to discuss if it makes sense if we are more liberal on this check and make some fields optional? Because in the schema none of the field is marked as required, see https://zalando.github.io/problem/schema.yaml

**Comment by netme** [comment]
Let me check the current implementation of `ProblemJson` library

**Comment by netme** [comment]
@fmueller, I have checked the zalando/problem repo. Found out that the minimal subset of parameters are `title` and `code`. 

I will create a small PR to make the rule more liberal.
