### ISSUE TITLE
Add Endpoint to Display List of Supported Rules

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#262]
Define the status endpoint which shows which rules are already implemented, e.g.:

`GET /rules`

which returns something similar to this:

```json
{
    "rules": [
        {
            "title": "Avoid Link in Header Rule",
            "code": "M001",
            "type": "MUST",
            "url": "http://zalando.github.io/restful-api-guidelines/hyper-media/Hypermedia.html" +
            "#must-do-not-use-link-headers-with-json-entities"
        },
        ...
    ]
}
```

The main benefit of it: on any Zally installation we can easily say what is the current configuration.

**Comment by mkulak** [comment]
Sounds good.

**Comment by fmueller** [comment]
Good idea.

I'd like to add: status of each rule, active or inactive. And a client can filter on this status per query parameter.

**Comment by netme** [comment]
Should we also use this endpoint later in UI?
