### ISSUE TITLE
Check is Swagger spec is compliant before running rules against it.

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#265]
Some rules can give you false positives when swagger spec is itself invalid. Error messages in this case can be very confusing. 
I propose to validate spec and if it's not valid emit special violation (without trying to check it with other rules). Much like we do if spec cannot be parsed.

**Comment by netme** [comment]
@mkulak that would be great. We can even go a bit further and do some swagger file linting like http://editor.swagger.io/ . Any ideas on the libs we can use for that?

**Comment by fmueller** [comment]
If the swagger spec is not compliant, the parser should throw an exception - my assumption so far. Is this not the case?

**Comment by mkulak** [comment]
No, this is not. See this issue: #261

**Comment by fmueller** [comment]
Ok, then we need this. 👍
