### ISSUE TITLE
Editor adding additional strings

### ISSUE THREAD

**Issue by wilq87** [zalando-incubator/zally#290]
Editor is behaving very strange (adding additional string values) when trying to edit properties in yaml file. Had a property "type:" and after pressing 7 times "t" after "e" letter it became:
"typetttttttddddddypettttttddddddypetttttddddddypettttddddddypetttddddddypettddddddypetddddddype:"

**Comment by fmueller** [comment]
@rbarilani Can you give your 2 cents please?

**Comment by rbarilani** [comment]
@fmueller Working on it.

**Comment by rbarilani** [comment]
@wilq87 Can you be so kind to give us some more informations to reproduce the bug:

* Browser Version
* The schema that you are trying to modify.

Thx in advance.

**Comment by wilq87** [comment]
@rbarilani 
Browser:
Version 57.0.2987.98 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

copy pasted API yaml for wholesale-article

**Comment by rbarilani** [comment]
@wilq87 I we deployed a new version can you be so gentle to try again with the same schema?

**Comment by wilq87** [comment]
@rbarilani works like a charm! thanks

**Comment by rbarilani** [comment]
@wilq87 👍 Great. Thanks for your contribution.
