### ISSUE TITLE
Show supported rules in web-ui

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#300]
After merging #275 we can create a page where all enabled rules are listed.

**Comment by Nagogus** [comment]
If it is still open, I can work on it as soon PR is merged. If nobody minds :)

**Comment by netme** [comment]
@Nagogus please do it. I will fix #275 tonight.

**Comment by fmueller** [comment]
@Nagogus You can start implementation now. Please update issue in our task board as well: https://github.com/zalando-incubator/zally/projects/1

**Comment by Nagogus** [comment]
@fmueller done. Shouldn't we show some kind of description of rules? It's not available in the response of endpoint.

**Comment by fmueller** [comment]
That's definitely a good point. Can you already integrate a not yet existing `description` field. We will add this in backend in next weeks.

**Comment by netme** [comment]
@Nagogus @fmueller, we don't have descriptions in rules now, we need probably some content first. Currently we have only descriptions patterns which are used for violation generation.

**Comment by fmueller** [comment]
Yes, plan is to integrate rules better with our guidelines and we could basically just use guideline text as description. But as I said, that's another user story. If the web ui can already deal with `description` field and displays it properly we are safe in web ui.

**Comment by netme** [comment]
Added an issue #310
