### ISSUE TITLE
Enhance monitoring of violated synonyms

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#301]
**As** an operator
**I would** like to see which synonym from synonym dictionary was violated
**so that** I can adjust the synonym dictionary on a data-driven approach

**Comment by mkulak** [comment]
@fmueller you prefer to see it in logs, db or you have in mind some other communication channel?

**Comment by fmueller** [comment]
We use `metrics` library for metrics already. Just have a look into `ApiViolationsController`. We need histogram per synonym like we have already for each rule.

**Comment by netme** [comment]
@fmueller , so the goal is to enable rule back, make sure that it always returns no violations and instead update metrics, right?
