### ISSUE TITLE
Add hint rule to not specify standard http error status codes if not necessary

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#312]
It's common practice and also encouraged in API reviews to not specify standard error status codes like 400, 404, 503 unless they have another meaning or special implementation/contract detail.

We should add a hint rule to check for this and inform API producer about the possibility to remove such declarations.

**Comment by akryvko** [comment]
created PR, it is **under development**
would like to clarify a few things:
- what is the API guide reference for this rule?
- am I right that all request types (post, get,,,) have the same set of standard error codes?

**Comment by maxim-tschumak** [comment]
Hi @akryvko!

> what is the API guide reference for this rule?

It's related to [Must: Use Specific HTTP Status Codes](http://zalando.github.io/restful-api-guidelines/http/Http.html#must-use-specific-http-status-codes). The described check should be a _HINT_ though.

> am I right that all request types (post, get,,,) have the same set of standard error codes?

It's not specified in the HTTP standard ([RFC-7231](https://tools.ietf.org/html/rfc7231#section-6.1)). Although, most of the response codes are related to a specific HTTP verb(s) (see overview in the guideline rule above).
