### ISSUE TITLE
Use Meter metrics instead of Counters

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#314]
**Current behavior**
Zally server collects counter metrics and exposes them via REST interface. However, counter metrics don't provide much meaning without a persistence and in the cloud setup (multiple stateless instances, auto-scaling, etc.).

**Expected behavior**
We should use [Meter](http://metrics.dropwizard.io/3.2.2/getting-started.html#gs-meters) metrics instead. They measure the rate of the events in specific time frames (e.g. 120 must violations in the last 15 minutes).

**Acceptance criteria**
- Counter metrics should be removed
- The `Meter` metrics should be collected for:
  - Each violation
  - Each violation type (must, should, could)
- Functional monitoring is set up (related to [internal-issue](https://github.bus.zalan.do/meta-api/management/issues/3))

**Comment by netme** [comment]
@maxim-tschumak special thanks for the ticket description 👍
