### ISSUE TITLE
Pluralize resource names should not fire for base path or possible base path extractions

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#315]
**Current behaviour**

The rule that one should not use singular in resource names also fires for parts of the `basePath` property. For instance, for `/api` it should not fire.

**Expected behaviour**

The rule `Pluralize resource names` only fires for the names in an endpoint which are not part of the `basePath` or be part of potential `basePath` extractions (combine it with output of Hint rule `Base Patch Extraction`).

**Comment by mkulak** [comment]
I'm a bit sceptic regarding "combining" part. It requires unique mechanism for rule interaction. For now rules are totally independent.
Do we really want to complicate this?

**Comment by netme** [comment]
Should we maybe make an exception for `api`?

**Comment by maxim-tschumak** [comment]
@netme @mkulak Should we exclude something else besides `api`? (any other base paths names you can think of?)

**Comment by netme** [comment]
@maxim-tschumak I will go for `/api` for now, but make it configurable so we can add more exceptions in the future
