### ISSUE TITLE
"Unused definitions" rule gives false positives 

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#321]
Currently it cannot handle "oneOf" with refs.
I cannot post direct link to related api definition for now (it's Zalando's internal one: balance/customs-tour-service). But later I will provide minified example.

**Comment by fmueller** [comment]
I think `oneOf` is not Open API 2.0 compatible. Such features came with Open API 3.0 and we also have a story to support Open API 3.0 in the backlog (see #204).

With this background I think we can close this, wdyt?

**Comment by mkulak** [comment]
@fmueller yes, you are right. I overlooked it.
