### ISSUE TITLE
web-ui: Refactor containers and http-client

### ISSUE THREAD

**Issue by Nagogus** [zalando-incubator/zally#323]
**As** a developer
**I want** to have clearer containers structure
**So that** I can easily navigate in the project

**Description** Currently we have navigation part in `violations` container. I suggest to move it to separate container `navigation` so it will be logical.

------------

**As** a developer
**I want** to have more powerful http client
**So that** I can send requests easier

**Description** We use [aurelia-fetch-client ](http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/2) it is HTTP client based on the Fetch API. It doesn't support query parameters. I suggest to switch to something more powerful so we don't need to write basic things ourselves. It can be [aurelia-http-client](http://aurelia.io/hub.html#/doc/article/aurelia/fetch-client/latest/http-services/3)

**Comment by rbarilani** [comment]
@fmueller moved here zalando-incubator/zally-web-ui#2

**Comment by rbarilani** [comment]
@fmueller can be closed?

**Comment by netme** [comment]
Closed since it was moved
