### ISSUE TITLE
Move Restful API Guidelines base URL to config variable

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#346]
While checking the existing rules I've found that Zalando Restful API Guidelines base URL is hard-coded in every rule. This leads to some inconsistencies, e.g. some of rules have `http` protocol and some `https`. 

Let's move base URL to application properties, so it will be consistent and we can change it any time.

**Comment by netme** [comment]
Giving up for now, cannot find a good balance between lean rules definition and keeping good architecture around it. Will try it out again soon.

**Comment by mkulak** [comment]
I propose to implement it as map "rule code" -> "rule url" in a config. Completely external to the rules logic. Assemble it on a higher level.
