### ISSUE TITLE
Run Go CLI Tests on Travis

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#353]
#### Acceptance criteria
1. Go CLI tests are run on Travis CI with every build
2. If possible, Go CLI test coverage report is uploaded to Codacy

**Comment by maxim-tschumak** [comment]
I don't have much experience with TravisCI, but as far as I understood, there is no support for multi-language environments. ([TravisCI issue](https://github.com/travis-ci/travis-ci/issues/4090))

**Comment by netme** [comment]
@maxim-tschumak , I think it's possible, we had built node.js together with Java before. We can check it on Monday, if it won't be officially supported we'll find some workaround.
