### ISSUE TITLE
Rename production spring profile

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#372]
Current Zalando specific OAuth implementation is covered as `production` spring profile. This is kinda misleading: we should rename it to `zalando-oauth` and also not make it the default profile. We have to adapt all deployment scripts accordingly after this change.

**Comment by maxim-tschumak** [comment]
@netme How do you feel about doing this one together? So that you also know how our deployment setup currently looks like.

**Comment by netme** [comment]
@maxim-tschumak yeah, we can do it together
