### ISSUE TITLE
Response status code check is too strict

### ISSUE THREAD

**Issue by ePaul** [zalando-incubator/zally#374]
#313/#340 added a check that verified that each operation only returns one of the status codes listed in http://zalando.github.io/restful-api-guidelines/http/Http.html#must-use-specific-http-status-codes (it also checks that the HTTP method fits).

I don't think that rule is meant to be understood as "don't ever use any other status code than those listed here" (the list says "Our list of most commonly used and best understood HTTP status codes") – so a violation against this should not be a "MUST" violation.

Also, it disallows the use of "default", which (with a response-body of a problem object) is IMHO fine.

**Comment by tkrop** [comment]
The guideline also states:

> Service providers should differentiate between technical and functional errors. In most cases it's not useful to document technical errors that are not in control of the service provider unless the status code convey application-specific semantics. The list of status code that can be omitted from API specifications includes but is not limited to ...

To comply to this rule while defining the proper response body actually requires our API describers to use `default:` to collectively announce all technical errors.

**Comment by dehora** [comment]
> I don't think that rule is meant to be understood as "don't ever use any other status code than those listed here"

Unfortunately, the guideline is pretty direct - "Must: Use Specific HTTP Status Codes" - what Zally is doing is not an unreasonable interpretation of that. I think this is an issue the with guidelines ignoring generic semantics of status codes, there's an issue open for it here: https://github.com/zalando/restful-api-guidelines/issues/233

**Comment by elvinx** [comment]
+1 from me. 

For example in case I want to return 415 for my GET and POST calls, I cannot according to this restriction. But in some particular cases it would make sense. I would also say that it should be "SHOULD" instead of "MUST"

**Comment by ePaul** [comment]
As I interpret the guideline (the full text, not just the title), it says "use status codes which are specific to your actual situation", not "use only those status codes which we list here". But maybe we need to reword it.

**Comment by fmueller** [comment]
Thanks @ePaul for bringing up this discussion. I think it is necessary. I'm with @dehora: the current implementation of this rule is reasonable. First, we need to change our guidelines - then we can update current implementation in Zally.

For time being and to help teams if they integrated Zally in their build process, we change it to `SHOULD` in Zally to not produce exit code 1 in CLI.
