### ISSUE TITLE
Remove Github Integration folder

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#398]
We decided against Github integration several weeks ago, so the folder should also be deleted.

**Comment by Yogendra0Sharma** [comment]
Hi @fmueller 
can I work on this issue?
what is the significance to removing the gh-integration folder?

**Comment by fmueller** [comment]
Hi @Yogendra0Sharma, this is only a cleanup task. We will not implement Github integration for Zally  - that's why this fold should be removed.

**Comment by netme** [comment]
@fmueller any details on that decision? It might be still a significant step forward for Zally visibility

**Comment by fmueller** [comment]
@netme With Zally we want to give feedback as fast as possible in development workflow. If we check an API definition in PR, this API has already been designed and feedback is quite late then. Also, the use case to check API definitions in PRs is quite rare compared to Zally usage via CLI or Web-UI when designing an API.

**Comment by netme** [comment]
@fmueller , OK, sounds reasonable. Then I'll put more effort on CLI tool :-)

**Comment by mkulak** [comment]
@fmueller following this logic CI is obsolete: we all want to have faster feedback on compilation errors while writing code.  IDE and compiler CLI give you that fast feedback. When we check if code compiles at all in PR, this code has already been written and feedback is quite late then ).

Jokes aside: web and cli Zally clients helps you to design your PR. Github integration provides you confidence that every member of your team actually takes Zally into account when he change something in swagger file.

**Comment by fmueller** [comment]
I'm totally with you @mkulak Maybe I was a bit to hard: I see the benefit and value of github integration. But given current team focus this is highly unlikely to happen in next months and having such a folder irritates potential users.
