### ISSUE TITLE
Fix unresolvable hostname in RestApiViolationsTest

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#399]
`RestApiViolationsTest.[shouldReturn404WhenHostNotRecognised,shouldStoreUnsuccessfulApiReviewRequest]` fail on some machines.

There is a chance that `bad.host.localhost` host can be resolved in some setups (because it's a generic subdomain of localhost).

To make the tests more stable we have to use another unresolvable hostname.

**Comment by fmueller** [comment]
Ok, this one is a really nice catch. ;-)

**Comment by maxim-tschumak** [comment]
Or, maybe, I just have a very weird local configuration :)
