### ISSUE TITLE
Disable Violation Pragmas

### ISSUE THREAD

**Issue by tfrauenstein** [zalando-incubator/zally#406]
feature enhancement idea:

When drafting an API, the API designer usually runs Zally multiple times.
He than checks Zallys violation output and decides how to handle each violation.
Sometimes API is changed as to avoid the violation, sometimes API is not changed on purpose -- often the case for SHOULD and MAY violations. 

Improve API designer convenience via support of pragma directives inside API definitions that disable checking of specific rules for specific OpenAPI elements. 
By this, API designers can avoid efforts for redundant checking of violations for multiple Zally runs during API evolution. 
It is also a must-feature for integration of Zally in automated CD or operation monitoring tooling.

**Comment by mkulak** [comment]
@tfrauenstein do I understand it correctly that you propose to modify swagger file itself? If so, can you give an example how these pragmas may look like? As the file with pragmas still needs to stay compatible with OpenAPI format.

As an alternative I can propose to add additional field to json payload (and corresponding cmd arg). This way we could avoid API file modification.

**Comment by tfrauenstein** [comment]
@mkulak Yes, I would prefer annotation inside OpenAPI definition to avoid multiple sources and correlation problems. As JSON does not support comments (IMO bad design choice, however) the only way I see is via specific fields. OpenAPI explicitly supports enrichments via vendor specific "x-" tags -- this would be the straight forward way to go for Zally pragma extensions.

**Comment by netme** [comment]
Really nice idea, I think many linters are supporting that.
We can also go a bit further and let Zally user disable rules from command line tool configurations.

**Comment by innokenty** [comment]
Hi guys, so I'm thinking of starting to implement this functionality. Let's discuss our visions of how this would look like.

We want to disable **specific rules** for **specific json nodes**, is that right? I checked the [OpenAPI docs](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/EXTENSIONS.md), basically every element contains the possibility to add vendor-specific tags (as @tfrauenstein correctly pointed out).

As I see it, we should agree on some specific syntax to disable any set of rules, that can be inserted on any level. Is this also the goal as you see it?

In my mind it should look kinda like this:
```json
{
  "swagger" : "2.0",
  "x-zally": {
    "disable": [
      "SnakeCaseInPropNameRule",
      "LimitNumberOfSubresourcesRule"
    ]
  },
  "paths" : {
    "/products" : {
      "get" : {
        ...
        "x-zally": {
          "disable": [
            "PluralizeResourceNamesRule"
          ]
        },
      }
    }
  },
  ...
}
```

**Comment by innokenty** [comment]
Implementing this seems to be a little tough though, because right now every rule executes it's own custom code getting the whole swagger doc as a parameter. Therefore checking these configs/exclusions will have to be done in every Rule separately.

**Comment by netme** [comment]
@innokenty how about making it a bit easier? We have rule codes, e.g. `M001`. My proposal will be the following:

```yaml
swagger: 2.0
x-zally-ignore:
  - M001
  - S001
...
```
and the same for inline definitions.

Maybe to keep it simple we can start with global level ignore definitions, it will already bring a lot of value and then later we can implement inline ignore statements. 

What do you think?

**Comment by innokenty** [comment]
Cool, codes are definitely better.
Yes, top level exclusions must be simple. I can implement that and then we'll see if we need more fine grained control.

**Comment by netme** [comment]
@innokenty one more proposal: can we also add an `X-Zally-Ignore` header support? It might be useful later for CLI tool to locally disable some checks.

**Comment by innokenty** [comment]
@netme Andrii suggests a parameter instead of a header, and I like it more actually. What do you think?
```
?ignore_rules[]=M001,S001&top=kek
```

**Comment by netme** [comment]
hm.. I personally not a big fan of that idea, however we can use access log later for some statistics. 

@maxim-tschumak , @maschleg what do you think about it?

If you will decide to go for URI params, please make them compliant: http://zalando.github.io/restful-api-guidelines/http/Http.html#should-explicitly-define-the-collection-format-of-query-parameters

Another option can be: CLI client injects ignore field in Swagger spec, then no changes will be required.

**Comment by innokenty** [comment]
ough, I think injections are way worse and more complex, than params

**Comment by maxim-tschumak** [comment]
Great ideas! my opinion:

**Server implementation**
I would go for top-level only `x-zally-ignore` field in the Swagger definition. This already has a great benefit for the users. We can still implement json-path based rule deactivation eventually.

**Communication Clients <-> Server**
Ignoring some rules has a direct effect on the query results. Proprietary X-Headers are deprecated. Only defined headers can be used (additionally they should be end-to-end) [related Guideline](http://zalando.github.io/restful-api-guidelines/headers/ProprietaryHeaders.html).
I would prefer to have query parameter in place (`csv` or `multi`).
Alternatively, we can do filtering on the client-side.

**Comment by netme** [comment]
Cool, then we have agreed :-)

**Comment by tfrauenstein** [comment]
Thanks for your initiative to move this feature forward. 
I like the proposals so far, but still have some questions/hints:

1) We need a concept of Rule-Id (Proposed to be a code like "M001"); requirements here: 
- Rule-Id is mastered by the Guidelines and easy accessible here 
   --> e.g. Rule-Id should be added as rule headline suffix
- Rule-Id must not change
   --> to be ensured by API Guild
- Rule-Id should be usable as link into Guidelines
   --> guideline PR
- Rule-ids / links should be used by Zally (e.g. for violation notification, disabling etc.)
   --> Zally impl: find a (simple) way to have Zally Rule-Ids as a consistent copy of guideline Rule-Ids
Hint: Out of scope for the time being: versioning of rules and its ids; rules may evolve and become more or less restrictive; rule check disabling holds for all versions 

2) Disabling of specific rules should be supported as local as possible.
For instance, rule "Should: Limit number of Sub-Resource Levels" only applies to resource paths and disabling should be for a specific path -- technically an OpenAPI "path item object" instance -- and not for the complete API. Hence disabling should only become effective, if it is done within the smallest context of the OpenAPI element relevant for the rule. Is this requirement agreed?

**Comment by maxim-tschumak** [comment]
@tfrauenstein thanks for your input.

**Rule-Id**
I propose to switch to static human and machine readable strings which include the rule title **without** the type of the violation (e.g. `secure-endpoints-with-oauth2.0`). It has multiple advantages:
* Static, no changeable names (identifiers of the rules)
* Human-readable, SEO friendly links to the Guidelines
* Links can be auto-generated
* Type of the rule can be safely changed

This will be easy to implement after the Guidelines are migrated to ASCIIDoc.

**Comment by maxim-tschumak** [comment]
> Disabling of specific rules should be supported as local as possible
I'll create an issue for this feature request.

**Comment by innokenty** [comment]
Unrelated: should I implement some parameter in the cli tool? If yes, then what did we agree on at the end?

**Comment by maxim-tschumak** [comment]
I think #446 is more important now @innokenty.

**Comment by innokenty** [comment]
Also much more complicated

**Comment by tfrauenstein** [comment]
@maxim-tschumak thx for response -- it would be great if you can take care of supporting the rule-id concept including consistency guidelines in course of its ASCII-doc-ization

Wrt. rule-ids standards I'm not convinced of non-numeric representation.
* human-readable is IMO less important -- easy rule access (via links) based on id is important
* ids as readable names tends to be too long -- at the end a (more or less short version of) the rule headline; ids short be short, easy to short-term memorize and easy to write in disabelling config and easy readable as appendix all rules headlines
* yes, ids should not be generated from content that may change -- so just simple sequence number (w/o rule must/may/should info) is to be preferred

**Comment by netme** [comment]
@tfrauenstein, @maxim-tschumak thanks for your input!

We have introduced Rule-IDs the time we introduced `ignore-rules` server configuration and we didn't thought on possible bigger scope for Rule-IDs.  

Current implementation of rules is assuming that IDs are:
- Sequential with prefix (we use `C` prefix for `MAY` because before it was called `COULD` and renaming it to `M` will conflict with `MUST`)
- Unique: we have an integration test which validates the uniqueness of every newly introduced rules

Would be really great if we can have cross-links between rules and API guidelines. This topic is also related to #150 and #151 and hopefully it will also help to increase visibility for API guidelines and Zally projects.

**Comment by maxim-tschumak** [comment]
@tfrauenstein @netme I'll take you points into account and come up with an ultimate Rule-Id concept for the Guidelines and Zally :)

**Comment by netme** [comment]
@maxim-tschumak I like the word "ultimate" ! 👍 

Please let me know if I can help.

**Comment by innokenty** [comment]
![getmediafile](https://user-images.githubusercontent.com/4004229/28611478-33cf6f46-71ec-11e7-911b-75109e971aab.jpeg)
