### ISSUE TITLE
Prepare a deprecation plan for Zally Java CLI

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#418]
Since we have agreed to move forward with Zally Golang CLI implementation `cli-go`, we need a plan™. 

### Acceptance criteria
1. A deprecation plan is created
1. A deprecation plan is discussed with Zally team
1. Follow up tickets are created and prioritized

**Comment by netme** [comment]
## Here is the plan™
- [ ] Track http client on server side and if it's not Zally 1.1 - show a server message which says "Your Zally client is outdated, please download a new  one from the Releases page"
- [ ] Remove `cli` folder. It will stay in Git history anyway
- [ ] Rename `cli-go` to `cli`
- [ ] Remove `CLI` tag on GH and rename `CLI-Go` to CLI
- [ ] Update main `README.md`
- [ ] Update `README.md` for Go CLI

@maxim-tschumak, @maschleg could you please share your feedback on it?

**Comment by maxim-tschumak** [comment]
@netme :+1:
Are you already working on the server impl? (checking the user agent header and responding with a deprecation message?) If not - I can do this!

**Comment by netme** [comment]
@maxim-tschumak thanks for checking.

Nope, I'm not working on it. Could you please create few tickets out of this list then?

**Comment by maxim-tschumak** [comment]
@netme Tickets have been created (#464 and @465).
