### ISSUE TITLE
Simplify handling of JSONs in HTTP controllers

### ISSUE THREAD

**Issue by innokenty** [zalando-incubator/zally#429]
Main goal is to get rid of `JsonNode` objects, manual parsing of jsons and hardcoded fieldname strings.

**Comment by netme** [comment]
Implemented in #428

**Comment by innokenty** [comment]
No wait, there is a bit more to simplify in other controllers! Or should it be one PR per issue?

**Comment by netme** [comment]
@innokenty sorry, didn't realise it :-) Nope, multiple PRs are OK. Could you please move it to back to "In Progress"?

**Comment by innokenty** [comment]
Did already!

**Comment by innokenty** [comment]
Implemented in #428 #430 #431 #432
