### ISSUE TITLE
Merge Zally and Zally-Web-UI Repositories ?

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#437]
**As a** Zally maintainer
**I want to** discuss if it makes sense to merge Zally and [Zally-Web-UI](https://github.com/zalando-incubator/zally-web-ui) repositories

**Comment by maxim-tschumak** [comment]
Pros:
* Everything in one place
  * Server and two client implementations (CLI and Web) are in the same place
  * Easier to promote and maintain?
* We can add docker-compose
* We can add more integration tests

Cons:
* Repository too big 
* CI setup is a bit more complex

My opinion:
We should move it to one [repository](https://github.com/zalando-incubator/zally)

**Comment by maxim-tschumak** [comment]
@netme @maschleg @mfellner What do you think?

**Comment by duergner** [comment]
For me the main question would be whether there are plan (or maybe even possibilities) for additional components on top of the Zally web service. If there are it might make sense to have different repositories and have a clear separation of concerns.

If it's more likely to have only the server, the CLI and the WebUI the benefit of a single repository with richer tests and especially easier getting started (docker-compose, only one README, etc.) should most probably outperform the more complex CI setup.

**Comment by netme** [comment]
I agree with @duergner , there are still more benefits to keep it in one mono-repo. Regarding CI - we are already having some hacks to make Go running on Travis, we can do something similar for node.js. 

+1 for keeping everything in one repo.

**Comment by mkulak** [comment]
It was like that before. What was original motivation for splitting those components into two separate repositories?

**Comment by netme** [comment]
@mkulak it was CI: Travis is not that good when working with different tech stacks

**Comment by maxim-tschumak** [comment]
New issue created: https://github.com/zalando-incubator/zally/issues/438.
