### ISSUE TITLE
Merge Zally and Zally-Web-UI Repositories

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#438]
**As** Zally maintainer
**I want** to have the source code of all components in one place
**So that** we can implement richer integration tests
**And** we can provide easier and better getting started guides and scripts

**Acceptance Criteria**
* [Zally Web UI](https://github.com/zalando-incubator/zally-web-ui) source code is moved to this repository.
* [Zally Web UI](https://github.com/zalando-incubator/zally-web-ui) links to the merged repository
* Travis configuration is adjusted and works
* Root README.md describes the project and all its components

**Comment by netme** [comment]
As an intermediate step we can include webui as a submodule.

Also we need to check if there is any way to keep the Git history of webui project. I will take a look on it.

**Comment by netme** [comment]
@maxim-tschumak , I've created a merge prototype in #447 . 

We still need to think how to transfer issues and how to deprecate the old repo.

**Comment by netme** [comment]
Commands which I've used:

```bash
git checkout master
git pull upstream master 
git checkout -b branch-name

git remote add webui git@github.com:zalando-incubator/zally-web-ui.git
git fetch webui master
git merge webui/master  --allow-unrelated-histories

git status
# Resolve conflicts in 
# .gitignore
# .travis.yml
# .zappr.yaml
# MAINTAINERS
# README.md
git commit
```
