### ISSUE TITLE
Prepare Release 1.1

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#457]
In order to prepare Release 1.1 we need to do the following:
- [x] Prepare release notes
- [x] Compile builds for Golang CLI tool for Windows, Linux and OSX
- [x] Check that basic workflows are working
- [x] Test Linux and OSX clients (sorry, we don't use Windows) 
- [x] Update README / gh-pages
- [x] Publish release on GH (and push v1.1.0 tag)
- [x] Check what can be already done from #418 
- [x] Send an email to Zalando mailing lists (@maxim-tschumak) 

**Target date:** 1.08.2017

**Comment by netme** [comment]
@maxim-tschumak could you please check if I've missed anything?

**Comment by maxim-tschumak** [comment]
Let's add a testing step (at least for Linux and OSX clients :) )

**Comment by netme** [comment]
@maxim-tschumak added

**Comment by maxim-tschumak** [comment]
Another task: after releasing, let's write an email with all the highlights (incl. merging the zally-web-ui repo) to open-source@ and tech-exchange@.
