### ISSUE TITLE
Deprecate zalando-incubator/zally-web-ui

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#461]
Since `zally-web-ui` is now merged back to `zally`, we need to deprecate `zally-web-ui` repository.

- [x] Remove all files from `zally-web-ui` repository
- [x] Add `README.md` with a small description and a link to `zally` repository
- [x] Move opened issues to `zally` repository

**Comment by netme** [comment]
@maxim-tschumak, @rbarilani anything else to mention here?

**Comment by maxim-tschumak** [comment]
Respective issue in the legacy repository: https://github.com/zalando-incubator/zally-web-ui/issues/16

**Comment by maxim-tschumak** [comment]
@netme Please review https://github.com/zalando-incubator/zally-web-ui/pull/17
and close https://github.com/zalando-incubator/zally-web-ui/issues/11 and https://github.com/zalando-incubator/zally-web-ui/issues/2
Thank you!
