### ISSUE TITLE
Chore: release and publish task

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#462]
Author: @rbarilani; Copied from the legacy Zally Web-UI repository.

Ideally we should have a npm script that release and publish a new version with one command.

```
$ npm run release [major|minor|path]
```

Pre-review:

- [ ] git checkout to new branch release/<next-version>
- [ ]  run tests
- [ ]  bump package.json version
- [ ]  build client assets
- [ ]  generate changelog
- [ ]  git add changes
- [ ]  git commit changes
- [ ]  git push changes
- [ ]  manually open a PR against master (or also this step can be automated?)

After review:

- [ ]  git add tag
- [ ]  git push tag
- [ ]  publish on npm

Ideally this task should run on a CI server but it should be possible to do that manually.

**Comment by maxim-tschumak** [comment]
Author: @EduardoAC 

Hi @rbarilani, I want to ask you about this issue in order to start working on it.

I understand the concept of one command release. However the pre-review steps I am not familiar with this kind of release system.

- if you want to create a new release from master, shouldn't it be already upgraded it the package.json version already?
- Why do you need the client assets on a PR? Couldn't you just generate then using prepublishOnly option?
- The content of the changelog need to be from the last release, Should I need to identify from the last tag or do you have another syste,?

I am a bit green on releasing this way, but it's a good exercise to come back to releases from CD

**Comment by maxim-tschumak** [comment]
Author: @rbarilani 

Hi @EduardoAC thx for looking into this.

> if you want to create a new release from master, shouldn't it be already upgraded it the package.json version already?

The release artifacts (changelog, bumped package.json, eventually compiled artifacts and so on) are produced on a specific release branch to be able to review before merging to master (at the point we really publish... add git tag and publish to npm)

> Why do you need the client assets on a PR? Couldn't you just generate then using prepublishOnly option?

We can remove that when we are stable enough but I find it beneficial when you wanna test a release candidate in another project without publishing on npm so you can use a git reference instead of a version.

> The content of the changelog need to be from the last release, Should I need to identify from the last tag or do you have another system?

I usually use this tool that do that for you: https://github.com/conventional-changelog/conventional-changelog

> I am a bit green on releasing this way, but it's a good exercise to come back to releases from CD

This process should be available as manual or and preferred run on CI/CD servers.

@EduardoAC BTW Those steps or procedures or approaches are not written in the stone so I'm really open to alternative proposal and discussions.

**Comment by EduardoAC** [comment]
@maxim-tschumak, thanks for your answer, I will have a look next week when I have a bit free time to prepare an small example so we can discuss further

**Comment by maxim-tschumak** [comment]
@EduardoAC Any updates? :)

**Comment by maxim-tschumak** [comment]
I propose to have a semi-automatic release process:
1. Creating a PR (bump version, adjust documentation and changelog)
2. Publishing is done manually (locally) after the PR is merged.

**Comment by EduardoAC** [comment]
Hi @maxim-tschumak, i didn't work con this feature since i got a second project con The evenings. Sorry for no communicate this more effective

**Comment by maxim-tschumak** [comment]
No problem @EduardoAC ! I'll take over this one.

There are a lot of open issues if you are interested :)
