### ISSUE TITLE
[GHE Integration] Lint APIs Using Zally Server 

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#481]
**As a** user of Zally GHE Integration solution
**I want** the GHE Integration to call Zally server to lint the APIs which are part of the pull request
**So that** the quality of the API specification can be measured and the developer/designer can get some feedback for a "free" review process

**Acceptance Criteria**
- Changed API definitions (from a pull request reported via Webhook) get linted by Zally Server
- Triggered on each PR webhook notification
- Review results are received and parsed

**Comment by netme** [comment]
Closed via #488
