### ISSUE TITLE
[GHE Integration] Report Review Results to PR

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#482]
**As a** Zally GHE Integration Solution user
**I want** to receive the results of the API review in the respective PR
**So that** I get a feedback about my API changes and react to them

**Acceptance Criteria**
- "No API changes detected" comment is sent if API specs haven't changed
- "API Review: #x MUST, #y SHOULD, #MAY, #HINT violations found" comment is sent if any violations
- "API Review: Wow! No violations! Great Job!! **Z**alando **A**PI **L**inter **L**oves **Y**ou :)"

**Nice to have**
Some nice/funny phrases for some special use cases (e.g. no MUST violations, only one violation, too many violations,..).

**Comment by netme** [comment]
Closed via #488
