### ISSUE TITLE
[GHE Integration] Integration server name

### ISSUE THREAD

**Issue by vecmezoni** [zalando-incubator/zally#490]
We need to come up with the name of Github integration service.

For now the suggestions are:
1. Bark (Zally's mascot is a dog, so it barks on bad PR's)
2. Octodog (Octo from Github's mascot Octocat)
3. OctoZally

**Comment by oleg** [comment]
1 :+1:

**Comment by Kaivalya1989** [comment]
How about zAllyMon like pokemon ? (Mon for Monitor)

**Comment by tkrop** [comment]
Forgive me my ignorance - can you explain me the three suggestions?

**Comment by vecmezoni** [comment]
I've added some explanation of the suggestions.
Feel free to suggest more options.

**Comment by netme** [comment]
1 👍

**Comment by akryvko** [comment]
+1 for zallyMon
and here goes mascot: 
https://s-media-cache-ak0.pinimg.com/originals/b1/72/b9/b172b97a5ecd719c6049bd3de90d3223.jpg
since dog and git hook.. =)

**Comment by maxim-tschumak** [comment]
1

**Comment by mkulak** [comment]
**G**ally**H**ally

Jokes aside, I vote for 1

**Comment by netme** [comment]
Also `GEIL` = Github Enterprise Integration Layer

**Comment by tkrop** [comment]
1 is fine 👍

**Comment by netme** [comment]
@vecmezoni should we close the issue?

**Comment by vecmezoni** [comment]
So the "bark" won!
