### ISSUE TITLE
Links broken on github page

### ISSUE THREAD

**Issue by EduardoAC** [zalando-incubator/zally#499]
404 page when you try to access to CLI and Web UI links on https://zalando-incubator.github.io/zally/

Current link for CLI: https://zalando-incubator.github.io/zally/cli/README.md
Correct link?: https://github.com/zalando-incubator/zally/blob/master/cli/README.md

Current link for Web UI: https://zalando-incubator.github.io/zally/web-ui/README.md
Correct link?: https://github.com/zalando-incubator/zally/blob/master/web-ui/README.md

![screen shot 2017-08-24 at 13 09 10](https://user-images.githubusercontent.com/2104706/29663922-ae8bd57e-88cd-11e7-8feb-85618ded8e90.png)

**Comment by netme** [comment]
Fixed in #503
