### ISSUE TITLE
Response enhancement or more detailed report page

### ISSUE THREAD

**Issue by superbenji** [zalando-incubator/zally#51]
Include count of must, should and could violations in the response in order to quickly get an overview in which condition the API spec is.
Or let the frontend (Zally report) calculate this numbers and display them.

**Comment by netme** [comment]
I've counted the amount of violations in CLI tool, see #52 .

Would be nice to get these counters directly from API to keep less business logic in clients.

**Comment by fmueller** [comment]
+1

I also see it as a nice addition to our API.

**Comment by netme** [comment]
Server part is implemented in #158, will fix CLI in another PR
