### ISSUE TITLE
[Rule Sets] 1. Ignore Rules by External Ids

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando-incubator/zally#558]
## Epic: [Rule Sets](https://github.com/zalando-incubator/zally/issues/551)

**Acceptance Criteria**
- Ignore functionality is based on the external rule id's (currently `guidelinesCode` field of the `SwaggerRule`)
- Same set of checks are executed per default (as now)

**Comment by roxspring** [comment]
Servers may be running with existing configurations that ignore e.g. the OAuth 2.0 rule referencing the internal id `M004`. Similarly swagger documents might be out there with a `x-zally-ignore: [M004]` declaration. Are we comfortable breaking these configurations as we transition to using the external id of `104` instead?

(we've discussed elsewhere that there are currently limited Zally servers in production making breakages more acceptable - I can confirm that we've not yet made heavy use of x-zally-ignore so a breakage would have very low impact for us in this case)

**Comment by maxim-tschumak** [comment]
> Servers may be running with existing configurations that ignore e.g. the OAuth 2.0 rule referencing the internal id M004. Similarly swagger documents might be out there with a x-zally-ignore: [M004] declaration. Are we comfortable breaking these configurations as we transition to using the external id of 104 instead?

Yes. There is no heavy use of `x-zally-ignore` extension @ Zalando too.
