### ISSUE TITLE
"zally rules" command line displays all rules without distinguishing active vs inactive

### ISSUE THREAD

**Issue by roxspring** [zalando-incubator/zally#566]
When running "zally rules" on the command line I notice that all rules are displayed the same even when some of them have been disabled at the server. There are a number of obvious ways we could fix this and achieve parity with the GUI:

1. Display "status: active" or "status: inactive" along side each rule
2. Provide additional command line flags "--active" and "--inactive" (or "--active false") so that we can choose which subset to display
3. Just stop showing the inactive rules because the user doesn't need to know about them.

Option (3) would be my preferred choice, ideally doing the same in the GUI for precisely the same reason.

**Comment by maxim-tschumak** [comment]
I also prefer option 3.
