### ISSUE TITLE
Remove Unused Rules

### ISSUE THREAD

**Issue by roxspring** [zalando-incubator/zally#576]
When preparing to work on a Rule having multiple Checks  #559 I noticed a few seemingly dead bits of code.

Would it be reasonable to delete and merge as described below before proceeding?

- Guideline 104 is implemented by 3 rules at the moment
  - `DefineOAuthScopesRule` - seems to do useful validation
  - `SecureWithOAuth2Rule` - does very little - reasonable to combine with above?
  - `UsePasswordFlowWithOauth2Rule` - is not annotated as `@Component` so not used - can we delete it?
- Guideline 174 is implemented by 2 rules
  - `AvoidSynonymsRule` - collects some metrics but never issues violations - can we delete it?
  - `CommonFieldTypesRule` - seems to do useful validation

**Comment by maxim-tschumak** [comment]
In my understanding this is what we have right now:

| Rule     | Guideline Ref |
|-------|------|
| `DefineOAuthScopesRule` | 104 |
| `SecureWithOAuth2Rule` | 104  |
| `UsePasswordFlowWithOauth2Rule` | 104 |
| `AvoidSynonymsRule` | 174  |
| `CommonFieldTypesRule` | 174 |

And this is how it will be after #551 is implemented:

| Rule   (Guideline Ref)        | Checks |
|-------------------------------|--------|
| Secure Endpoints (104)        | {`DefineOAuthScopesRule`, `SecureWithOAuth2Rule`, `UsePasswordFlowWithOauth2Rule`} |
| Use common field names (174)  | {`AvoidSynonymsRule`, `CommonFieldTypesRule`} |

Check implementations are based on the implementations of what we call a 'rule' right now. 

I don't quite understand why you want to merge/delete some of these rules.

**Comment by roxspring** [comment]
Just wanting to see if there are any shortcuts available before the next round of work is all. The two below seem particular pointless and in the absence of further information I lean towards the "delete" option in both cases:

# UsePasswordFlowWithOauth2Rule
Currently this is not annotated as a component and so **cannot** be used as a rule. (All it's doing is wasting nanoseconds of compiler time!) I think we need to do one of the following:

- If it's good: Annotate it so that it becomes enabled
- If it's broken and temporarily disabled: Comment in the code to explain why it's not annotated.
- If it's just not to be used: Let's delete it rather than let it gather dust.

# AvoidSynonymsRule
This is coded such that it collects metrics and **never** produces a violation. Guideline 174 doesn't even mention avoiding synonyms. One of the following should happen:

- Identify a database of synonyms, start using it, and enable the rule.
- Somebody confirms that they care about the metrics being collected for now, probably still delete the unreachable code.
- Admit that "Avoid Synonyms" is impractical to automate, not part of any guideline, so should be deleted.

If it's to become standard practice to analyse swagger files and record metrics, presumably while researching future rules, let's find a way to do it without pretending that they are rules in themselves.

**Comment by maxim-tschumak** [comment]
I've double checked the rules and implementations.

**UsePasswordFlowWithOauth2Rule** -> I would annotate this check and set the violation type to `SHOULD`:
- http://zalando.github.io/restful-api-guidelines/#104 is a `MUST` rule, but
- [..] API endpoints *should* always set `flow: password` and ignore this information. [..]

**AvoidSynonymsRule** -> I would remove this one
- The guideline doesn't provide any dictionary or examples
- Statistics are not persisted in the database
