### ISSUE TITLE
CONTRIBUTING asks for impossible things

### ISSUE THREAD

**Issue by roxspring** [zalando-incubator/zally#608]
Just looked at the CONTRIBUTING file for the first time in a while and was curious to see that it asks contributors of pull requests to:
1. "Assign yourself so we know you're working on it"
2. "If you're still working on it, add the **under development** label"

Unless I'm much mistaken, neither of these are things that the wider community are permitted to do.

**Comment by maxim-tschumak** [comment]
Are you missing the rights to self-assign an issue or adding a label?

**Comment by roxspring** [comment]
Both. 

Thanks,

Rob
