### ISSUE TITLE
Auto detection of rules from classpath. 

### ISSUE THREAD

**Issue by thomasabraham** [zalando-incubator/zally#61]
If any class is implementing the rule interface, it should automatically be picked up and validated.

**Comment by fmueller** [comment]
Furthermore, I'd like to make it configurable: auto-detection of rules is default but you should be able to configure set of rules by configuration parameter in application.properties. I think we can implement this with another Issue - but just to mention it.

**Comment by netme** [comment]
Later we should also make an option to disable some validators. In this case the product can be used in many other companies. 

Inspiration: http://flake8.pycqa.org/en/latest/user/configuration.html#project-configuration

**Comment by thomasabraham** [comment]
I'm proposing the following design for this issue. 

A new interface `RulesManager` will be added with methods `List<Rule> getRules();` and `List<Rule> getRules(String package);`.

RulesValidator class won't implement Rule interface anymore since it is not a rule but a wrapper which validates all the other rules. Instead it will autowire `RulesManager` and use it to get all the rules that needs to be validated.

Any class in classpath which implements Rule interface will be added to the list of rules unless it is marked with `@IgnoreRule` annotation. Based on some configuration RulesValidator class can either validate all the rules available or only those rules in certain package. 

Rules will be organized into packages in a meaningful way. For example all zalando api guidelines rules will be in our current package for rules but additionally inside sub packages for must, should, and could. A third party can implement his rules in a totally different package. In future based on configuration a rules artifact (jar containing implementation of rules) can be fetched and included at runtime.

**Comment by fmueller** [comment]
@thomasabraham Thank you for your detailed design idea. I really like your idea of making it more configurable. Great idea with just linking jar files on classpath, this would open this linter for other organizations. :-)

Furthermore, I'd like to propose following changes to your approach - what do you think about those:

- no annotation based configuration: configuration of rules should be done solely via parameters which can be submitted via properties file and environment variables - intention is: keep it easy configurable in docker container and any other runtime environment

- for instance, each rule can therefore implement a getRuleIdentifier() : String method which returns specific rule identifier which can be used later in configuration parameters where rules are included, excluded or grouped

- grouping rules by violation type is an artificial grouping imho: what do you think about grouping them semantically by the characteristic they are checking? for instance, all naming related rules go into naming subpackage, all http related ones in http subpackage.

**Comment by mkulak** [comment]
TBH I don't understand the usecase for this feature.
Who will configure list of rules? How often this person will want to change it afterwards?

During hackweek there was 1 pain point associated with it: number of implemented rules grew quickly and it was annoying to add them manually. Since most of the tractable rules are already implemented this pain is gone.

**Comment by netme** [comment]
@mkulak as far as I understand, we are solving 1 important problem here: bring Zally to other companies outside Zalando to make sure that they can introduce their rules easily.

**Comment by fmueller** [comment]
Furthermore, I think we should separate Auto Discovery of Rules and Configuration of Rule Set in separate tasks. Agree @netme @thomasabraham @mkulak?

**Comment by thomasabraham** [comment]
I agree, Auto Discovery of rules part should only be concerned with identifying all the rules available in classpath. I'll split the issue into two.

**Comment by netme** [comment]
👍🏻 yes, makes sense
