### ISSUE TITLE
Incorrect 'Response As JSON Object:' violation

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-incubator/zally#63]
Given the following swagger spec:

```yaml
swagger: '2.0'

info:
  version: "0.0.1"
  title: API Example

schemes:
    - "https"
basePath: /
produces:
  - application/json
consumes:
  - application/json

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    tokenUrl: https://tokeninfo.example.com
    scopes:
      uid: Unique identifier of the user accessing the service.

security:
  - oauth2: [uid]

paths:
  '/resources':
    get:
      summary: List all resources
      responses:
        200:
          description: List of all resources.
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                    '$ref': '#/definitions/Resource'
        500:
          description: Unexpected error

definitions:
  Resource:
    type: object
    properties:
      name:
        type: string
```

I get this violation when running the CLI:

```
$ cli/bin/zally swagger.yaml
Found the following MUST violations
===================================
Response As JSON Object:
	Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
	/resources/GET/200

Summary:
=======
COULD violations: 0
SHOULD violations: 0
MUST violations: 1
```

Since the response type of `/resources/GET/200` is:

```json
{
  "items": [Resource,]
}
```

I would not expect it to be a violation.

**Comment by fmueller** [comment]
Thank you for providing us with this detailed bug description. I could reproduce the issue with you swagger example. There is also a bigger issue with this rule implementation. Fixing it will take some time. But I'm on it.

**Comment by mkulak** [comment]
I would like to pick that one. 
@fmueller are you in a process of fixing it or I can pick that?

**Comment by fmueller** [comment]
I only have a test so far, to verify it. Go ahead, if you like :-)

**Comment by ishishov** [comment]
@fmueller, I think we also discussed this case and agreed that response type cannot be array, top level should be json object and array should be wrapped in another class(ref)? Or did I miss something? If array is allowed, I can fix it once I come back from holiday on Monday if it's not fixed already.

**Comment by fmueller** [comment]
@ishishov Enjoy your holiday. I think we had a misunderstanding here. ;)

First entity in response have to be an object - what's in the object doesn't matter. So, the given example swagger file is totally valid.

**Comment by ishishov** [comment]
@mkulak are you still on it? if so, I'll pick something from the issue backlog

**Comment by mkulak** [comment]
I'm literally in the process of fixing it right now

**Comment by mkulak** [comment]
@ishishov I pushed all my code to branch #63-incorrect-json-object
It contains test + draft implementation. You can continue from here (see failed test for spp api)

**Comment by ishishov** [comment]
@mkulak sounds good, thanks
