### ISSUE TITLE
Filtering applicable rules from available rules via configuration. 

### ISSUE THREAD

**Issue by thomasabraham** [zalando-incubator/zally#75]

**Comment by netme** [comment]
Since we are touching rule orchestration in #82 it makes sense to postpone implementation until grouping will be ready.

**Comment by fmueller** [comment]
This is not related to grouping in response payload. This issue is about enabling and disabling of rules in the server, so which rules should be checked on an api-violations request.

**Comment by netme** [comment]
@fmueller it was more related to escaping possible merge conflicts, nothing related to feature itself :-)

**Comment by netme** [comment]
Proposal for implementation:
- Zally API should have a special optional array in request body called `ignore_rules` like:

    ```json
    {
         "api_definition": {},
         "ignore_rules": ["Rule1", "Rule2", "Rule3"]
    }
    ```

- To simplify the usage, we need to give rules short names / codes and document them somewhere, e.g. `M001: MUST Avoid Link in Header` or something similar.

Any concerns?

**Comment by netme** [comment]
Maybe it's time to mention @fmueller and @mkulak 😺

**Comment by fmueller** [comment]
Thanks for pointing us on this. I totally overlooked your proposal, sorry for this.

I propose to keep this configuration on server-side for the reason that server decides about rule implementations and also should decide about which rules will be applied.

So, my proposal: Put `ignore-rules`configuration field in server application.properties file. In this config parameter you can server-wise configure which rules should be ignored for a server.

**Comment by netme** [comment]
@fmueller many thanks for checking ! That sounds reasonable, right. It will help to keep a single source of truth, will do it using `ignore-rules` way.

How about short names? Should we do something like:

```
ignore-rules=M01,M02,S01,C01...
```

or should we use full class names:

```
ignore-rules=HttpHeadersRule,KebabCaseInPathSegmentsRule,...
```

**Comment by fmueller** [comment]
Ok, then we also do it with short names if other linters are doing it same way.

**Comment by netme** [comment]
Cool, I will start implementation then! Thanks for checking!
