### ISSUE TITLE
Introduce new rule type "Hints"

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#81]
Let's discuss the following use case:
- User wants to implement `feature A` of API (e.g. HTTP headers support)
- Zalando has already a lot of experience in implementing `feature A` and uses a `library B` for that
- Zally spots that user implements a `feature A` 
- Zally gives a user recommendation to use `library B` during implementation and points to some usage manual.

**Comment by mkulak** [comment]
1. Here we assume that user follows "API first" principle. Which is not necessarily true. I mean at the moment of API spec validation this API could already be implemented.
2. Swagger is language/tech stack agnostic. As long as you stick to REST API you can get value from using swagger. On the contrary libraries are highly dependent on language/tech stack. To make it useful for user we need to ask what tech he is using or suggest possible solutions for several popular tech stacks. And even then Zally have no clue about user's goals, limitations and design decisions related to his system. 

I don't think we can provide much value to the user with such suggestions.

**Comment by netme** [comment]
@mkulak, I agree, maybe it's good to provide few real use-cases first.

**Comment by fmueller** [comment]
@mkulak @netme I see this more in the sense of giving API designers more helpful hints. For instance, if Zally recognizes that the API uses pagination, we can give recommendation to consider cursor-based pagination (another rule).

**Comment by netme** [comment]
@fmueller, yes, that also can work. So maybe we can rename it to "Hints"?

**Comment by netme** [comment]
My main idea was to make this tool not only complaining about the issues, but also helping you to improve your APIs and learn.

**Comment by fmueller** [comment]
Yes, the idea is great. :-)

So, next would be to go through our guideline rules and see where we can give such hints. All hints should be based on used rules in given API definition.

**Comment by netme** [comment]
I can propose that someone will look on the list of rules first and then we can discuss what we can implement (the same way like we did for Must, Should and Could during the hackweek). 

@fmueller should I create an investigation task for that?

**Comment by fmueller** [comment]
Yes, sounds good. 👍

**Comment by netme** [comment]
Investigation task: #88

**Comment by netme** [comment]
Also created general implementation tasks #89 and #90

**Comment by fmueller** [comment]
Since it is implemented, I close this issue.

**Comment by netme** [comment]
Thanks for closing it, completely forgot about it.
