### ISSUE TITLE
Current Zally's API spec is incomplete

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#85]
Description of endpoint `/api-violations` doesn't contain any info on how to actually send swagger spec for linting. 
 
```yaml
paths:
  '/api-violations':
    post:
      summary:
        Retrieves list of API violations based on the uploaded swagger file
      description:
        Retrieves list of API violations based on the uploaded swagger file
      parameters:
        - $ref: '#/parameters/Authorization'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: API swagger is OK
          schema:
            $ref: '#/definitions/LintingResponse'
        400:
          description: Input file not parsable
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
        default:
          description: An array of error objects
          schema:
            $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
      security:
        - oauth2:
          - uid
```

Also description "Retrieves list of API violations based on the uploaded swagger file" sounds very confusing to me - do I really need to upload my swagger file prior to calling this endpoint? 

I propose to add actual spec for request body and change description.

**Comment by fmueller** [comment]
The description is just wrong, you are right.

The other point I don't understand really as there is an entity definition for LintingRequest in the swagger file.

**Comment by mkulak** [comment]
LintingRequest is not referenced in parameter list for this path.

Also there are several validation errors of our current API spec (just paste it to http://editor.swagger.io/#/ to see them)

**Comment by fmueller** [comment]
Ok, I see.

**Comment by netme** [comment]
Can be a good integration test: lint our own swagger specification.
