### ISSUE TITLE
Instructions "how to build and run cli tool" are incomplete

### ISSUE THREAD

**Issue by mkulak** [zalando-incubator/zally#86]
In [cli/README.md] I see following instructions:
1. cd cli
2. ./gradlew bin
3. ./bin/zally

After doing it on a clean project I get: 
`Error: Unable to access jarfile /Users/mkulak/src/zally/cli/bin/zally.jar`

As far as I understand shell script expects jar-file to be located in his dir but gradle by default places it in build/libs.
So we need either add to readme additional step like `copy build/libs/zally.jar to bin` or add copying to gradle task.

**Comment by fmueller** [comment]
Hm, can you confirm this behavior @netme?

**Comment by netme** [comment]
Actually this is a long story, for some reason `copy` command of `gradle` doesn't work properly :-( We are already copying the `.jar` file after creating `oneJar` and after `building`.

https://github.com/zalando-incubator/zally/blob/master/cli/build.gradle#L44

I will do some further investigations on this topic

**Comment by fmueller** [comment]
Ok, than I assign you. :-) Ping me if I can help you in some way

**Comment by netme** [comment]
Started investigations
