### ISSUE TITLE
Define the list of rules for Hints section

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#88]
In order to make Zally more friendly to end users, we need to implement an additional section called "Hints". 

### Example: 
> If Zally recognizes that the API uses pagination, we can give recommendation to consider cursor-based pagination and provide a link.

### Goal:
- Create the list of such rules
- Prioritise them
- Create tickets to implement them

**Comment by fmueller** [comment]
This is an ongoing tasks, more an activity - always look for improvement. So I close this for now.
