### ISSUE TITLE
Add an Integration Test to Run on Travis.CI

### ISSUE THREAD

**Issue by netme** [zalando-incubator/zally#92]
In order to make sure that CLI tool is not broken, we can add a small integration test which:

1. Compiles and starts Zally Server
2. Compiles Zally CLI
3. Runs few scenarios with local and remote files

In order to keep it simple, we can use bats framework for that.

**Comment by fmueller** [comment]
This would help a lot, I think. Good suggestion. :-)

**Comment by netme** [comment]
Thanks, I will take care of a small prototype then.
