### ISSUE TITLE
Add optional OAuth2 flow to Web UI

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#94]
Some environments make an integration with OAuth2 mandatory, therefore it should be optional possible to secure the Web UI (/try and /results endpoints).

Probably use https://github.com/zalando/oauth2-client-js for this.

**Comment by jbellmann** [comment]
With what systems do you want to authenticate?

**Comment by fmueller** [comment]
Like https://github.com/zalando-incubator/api-discovery/tree/master/swagger-ui it should use our AD login page. It should be configurable if you want to have this and if yes, which endpoints are used for Single Sign On.

**Comment by fmueller** [comment]
Depends on #170
