### ISSUE TITLE
_links field is not whitelisted

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#96]
_links field should be whitelisted in each rule, it violates our syntax rules in the guidelines but is also defined as default field for links in our guidelines. Currently Zally creates violations for it.

**Comment by mkulak** [comment]
@fmueller AFAIU the only rule that is related is SnakeCaseInPropNameRule
Do you know about any other rules that need to be changed to fix this issue?

**Comment by fmueller** [comment]
It's only related to this rule.

**Comment by fmueller** [comment]
Was re-introduced by a refactoring.
