### ISSUE TITLE
Add synonym dictionary as configurable rule

### ISSUE THREAD

**Issue by fmueller** [zalando-incubator/zally#97]
In our microservice architecture at Zalando (and I guess this holds true for other environments as well) we have a common set of property names like customer id, order id and so on. Such terms should be the same across all APIs. I think it would be a great value add if one could configure a synonym dictionary where alternative names for such general property names are listed and once an API uses such a synonym and not the general name a violation is created.

This dictionary should be configurable, for instance by a simple text file.

e.g.:
customer Id -> synonyms: cId, c-id, custId, cust_identifier...

**Comment by mkulak** [comment]
I like this idea

**Comment by fmueller** [comment]
A first list of common fields should be taken from rule "Must: Use common field names" in http://zalando.github.io/restful-api-guidelines/common-data-objects/CommonDataObjects.html

But only as starting point to build a synonym list. Check of type and format of these field is already implemented by another rule.
